[package]
name = "query-optimizer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde-wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true }

# For SQL parsing (uncomment in production)
# sqlparser = "0.39"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
